### ISSUE TITLE
how add plugin?

### ISSUE THREAD

**Issue by aacassandra** [vue-ioc/vue-ioc#1]
hello, thank you for the source code you made. is it possible for me to add a plugin on httpservice.ts that I declared in the constructor like Angular?

example:
in httpservice.ts

import { Example } from "blabla";

export class HttpService{
 constructor(
public example:Example
}{}

im trying like this and im getting error?
any idea? 
thankyou sir

**Comment by gejgalis** [comment]
Hello @aacassandra,
 
All you need is to put `@Injectable()` decorator above `HttpService` class and also above declaration of `Example` class, then you need to declare both of them in `@Module({providers: [...])` section.

If there are still errors, please provide error messages.

**Comment by aacassandra** [comment]
thankyou sir, thats work :)
