### ISSUE TITLE
Error in beforeCreate/beforeDestroy hook: "Error: NULL argument"

### ISSUE THREAD

**Issue by daricvn** [vue-ioc/vue-ioc#10]
Hello guys, 
Currently I got this error when trying to use Vue ioc.
However, it's not working as expected. I decided to change back to inversify-props temporary
Here's my code:
main.ts
```javascript
import Vue from "vue";
import { VueIocPlugin } from '@vue-ioc/core'
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "./quasar";

Vue.config.productionTip = false;
Vue.use(VueIocPlugin)

new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app");
```
App.vue
```javascript
import Component from 'vue-class-component';
import Vue from 'vue'
import AppService from './services/AppService';
import { ProvideReactive } from 'vue-property-decorator';
import { Module, InjectReactive, Inject } from '@vue-ioc/core';
import UserService from './services/UserService';
import Header from './components/parents/Header.vue';

@Module({
  providers:[
    AppService, UserService
  ]
})
@Component({
  components:{
    Header
  }
})
export default class App extends Vue{}
```

AppService.ts
```javascript
import { CONFIG } from '@/config/config';
import axios from 'axios';
import { Injectable } from '@vue-ioc/core';

//
// Only use for Desktop's App
@Injectable()
export default class AppService{
    // public readonly AppName = "Cleverdocs";
    isDeskApp: boolean = false;
    public async RequestLicense(): Promise<boolean>{
        if (CONFIG.VIEW_SERVICE){
            const result = await axios.get(`${CONFIG.VIEW_SERVICE}/app/ping`);
            this.isDeskApp = !!result.data;
            return !!result.data;
        }
        this.isDeskApp = false;
        return false;
    }
}
```

Header.vue
```javascript

import Component from 'vue-class-component';
import Vue from 'vue'
import AppService from '../../services/AppService';
import { InjectReactive, Inject } from '@vue-ioc/core';

@Component
export default class Header extends Vue{
    @Inject() public appService!: AppService;

    mounted(){
        this.appService.RequestLicense();
    }
}
```

Here's the message I received:
vue.runtime.esm.js?2b0e:1888 Error: NULL argument
    at Lookup.hasKey (lookup.js?0300:61)
    at getBindings (planner.js?87b3:123)
    at _getActiveBindings (planner.js?87b3:30)
    at _createSubRequests (planner.js?87b3:85)
    at Object.plan (planner.js?87b3:136)
    at eval (container.js?f457:317)
    at Container._get (container.js?f457:310)
    at Container.get (container.js?f457:230)
    at VueComponent.beforeCreate (vue-ioc-core.js?45e1:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)

As far as I know, it turns out that the **var Service Identifier** was null when the Inject is invoked.
It happens when beforeDestroy usually even you include **"emitDecoratorMetadata": true** in tsconfig

Thank you for your help.

**Comment by gejgalis** [comment]
@daricvn please provide exact versions of your dependencies so I could recreate this error: typescript, vue, vue-class-component, vue-router, vuex and quasar

**Comment by daricvn** [comment]
Hello @gejgalis ,
Here's the list of my app dependency:

>     "@ckeditor/ckeditor5-build-decoupled-document": "^16.0.0",
>     "@ckeditor/ckeditor5-page-break": "^16.0.0",
>     "@ckeditor/ckeditor5-vue": "^1.0.1",
>     "@quasar/extras": "^1.0.0",
>     "@types/crypto-js": "^3.1.43",
>     "@vue-ioc/core": "^0.1.1",
>     "axios": "^0.19.1",
>     "core-js": "^3.4.4",
>     "crypto-js": "^3.1.9-1",
>     "inversify": "^5.0.1",
>     "inversify-props": "^1.4.9",
>     "quasar": "^1.0.0",
>     "reflect-metadata": "^0.1.13",
>     "vue": "^2.6.11",
>     "vue-ckeditor5": "^0.4.1",
>     "vue-class-component": "^7.2.2",
>     "vue-property-decorator": "^8.3.0",
>     "vue-router": "^3.1.3",
>     "vuex": "^3.1.2",
>     "vuex-class": "^0.3.2"

In case you would like to reproduce the issue, please clone this repository, go to vue-app and run npm start, right there, you will see an editor with File menu, click on File menu, click on any context display there, you will see the error.
https://github.com/daricvn/cleverdocs/tree/master/Cleverdocs/app/vue-app

**Comment by gejgalis** [comment]
@daricvn thank you for letting me easily reproduce this bug. It seems that destroyment of component not owning `@Module` decorator causes not necessary destroyment of IoC container. I'll fix this bug today.

**Comment by gejgalis** [comment]
@daricvn issue has been fixed. Please bump to @vue-ioc/core 0.1.2 and let me know if that works for you.

**Comment by daricvn** [comment]
@gejgalis 
It works perfectly for me now.
Thank you very much.
