### ISSUE TITLE
providedIn: undefined

### ISSUE THREAD

**Issue by abratko** [vue-ioc/vue-ioc#24]
Hi!

I use @Module with factory function as in readme and get error 

`Error in beforeCreate hook: "Error: Invalid providedIn: undefined"`

Is `providedIn` required in this case? Or is it issue?

Error disappear if providedIn setted

**Comment by gejgalis** [comment]
@abratko It shouldn't be required. I'll fix it today.

**Comment by gejgalis** [comment]
@abratko Bug has been fixed in `0.2.2`
