### ISSUE TITLE
Skip Base class @injectable checks

### ISSUE THREAD

**Issue by abratko** [vue-ioc/vue-ioc#25]
Inversify container has option  skipBaseClassChecks
https://github.com/inversify/InversifyJS/blob/master/wiki/inheritance.md#workaround-e-skip-base-class-injectable-checks

is there way to set up this option?

**Comment by gejgalis** [comment]
@abratko I've changed default container options with `skipBaseClassChecks` to `true`. Moreover if you need to override some Inversify container options you may use plugin options:

```typescript
Vue.use(VueIocPlugin, {
  containerOptions: {
    // options of Inversify container:
    // https://github.com/inversify/InversifyJS/blob/master/wiki/container_api.md#container-options
  }
})
```
