### ISSUE TITLE
peerDependencies conflict 

### ISSUE THREAD

**Issue by abratko** [vue-ioc/vue-ioc#28]
My project has dependecies  from   "vue-class-component": "^7.2.6" and vue-ioc/core has  peerDependencies from   "vue-class-component": "^6.0.0".

So, when i install package i get

warning " > @vue-ioc/core@0.2.2" has incorrect peer dependency "vue-class-component@^6.0.0".

Can peerDependencies be upgraded  to latest stable major version?

**Comment by gejgalis** [comment]
@abratko I've just released new version `0.2.3.` with following `peerDependencies`:
```
  "peerDependencies": {
    "inversify": ">=4.5.0",
    "reflect-metadata": ">=0.1.12",
    "vue": "^2.5.0",
    "vue-class-component": ">=6.0.0"
  },
```

Please re-open this issue if still doesn't work for you.
